### ISSUE TITLE
Any reason to use nvcc v11.8 specifically or will 12.x be ok?

### ISSUE THREAD

**Issue by danpetry** [conda-forge/cccl-feedstock#14]
### Comment:

We haven't built the conda package for nvcc v11.8 and don't have CI machines with cudatoolkit installed, so compiling this with nvcc v12.3 would be much easier if possible. If we (anaconda) are only going to be depending on this cccl package for other cuda packages v12.4 and above, I guess building cccl with 12.3 is fine? @jakirkham

**Comment by jakirkham** [comment]
For the build? Was just picking one CUDA version to not have a matrix. Yeah think any version should be fine. CCCL is just header only

For the packages themselves, we ignore `run_exports` of the CUDA compiler to make sure the packages can be installed on any CUDA version

CCCL articulates its CUDA version support in [this README section]( https://github.com/NVIDIA/cccl?tab=readme-ov-file#cuda-toolkit-ctk-compatibility ), which is quite broad

**Comment by jakirkham** [comment]
Going to close this as answered. If new questions come up, please feel free to raise a new issue

**Comment by danpetry** [comment]
yes thank you
