### ISSUE TITLE
Transition to use the CCCL monorepo 

### ISSUE THREAD

**Issue by leofang** [conda-forge/cccl-feedstock#2]
Maybe starting at v2.2.0?

**Comment by jakirkham** [comment]
@jrhemstad when would you recommend to make this move? 2.2.0 or another version?

**Comment by jrhemstad** [comment]
The monorepo has been the source of truth since [2.2.0](https://github.com/NVIDIA/cccl/releases/tag/v2.2.0), so that seems like the right place to start.

**Comment by jakirkham** [comment]
Thanks Jake! 🙏

**Comment by jakirkham** [comment]
@conda-forge-admin , please update version

**Comment by jakirkham** [comment]
Have implemented with an update to 2.2.0 in PR: https://github.com/conda-forge/cccl-feedstock/pull/6

Please let us know if we need to add anything else there
