### ISSUE TITLE
Add the `cuda` team as maintainers?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cccl-feedstock#3]
While this `cccl` package is not part of the CUDA Toolkit (the counterpart is `cuda-cccl`), it might make sense to be maintained by the same group of people, at least for the purpose of receiving notifications from this feedstock.

**Comment by jakirkham** [comment]
This seems ok. The current maintainers are already a subset of that group. So makes sense to make the change

**Comment by jakirkham** [comment]
@conda-forge-admin , please add user @conda-forge/cuda

**Comment by jakirkham** [comment]
Interesting seems we need a new issue to do that: https://github.com/conda-forge/cccl-feedstock/issues/4

Handling in PR: https://github.com/conda-forge/cccl-feedstock/pull/5
